#!/bin/bash

PRODUITS=./produits.txt

while IFS= read -r _produit; do
  if [ -f ${_service}/install ]; then
    echo "Execution de la suppression du produit ${_produit}"
  else
    echo "Le produit ${_produit} n'a pas de script de suppression = Rien a faire"
  fi   
done  < <(cat "${PRODUITS}"|sed -e /^$/d|grep -E -v "^#")
